export const t = {
  siteName: "RANKIS.LT",
  search: "Paieška",
  searchPlaceholder: "Ieškoti prekių, kodų...",
  cart: "Krepšelis",
  cartEmpty: "Krepšelis tuščias",
  addToCart: "Į krepšelį",
  added: "Pridėta",
  inStock: "Yra sandėlyje",
  outOfStock: "Užsakoma",
  code: "Kodas",
  brand: "Gamintojas",
  price: "Kaina",
  vat: "su PVM",
  save: "Sutaupote",
  home: "Pradžia",
  catalog: "Katalogas",
  all: "Visos prekės",
  allIn: "Visos",
  filters: "Filtrai",
  reset: "Išvalyti",
  apply: "Taikyti",
  brands: "Gamintojai",
  priceRange: "Kaina, €",
  from: "Nuo",
  to: "Iki",
  onlyInStock: "Tik turimos",
  showAll: "Rodyti visus",
  showLess: "Rodyti mažiau",
  sort: "Rikiuoti",
  sortPopular: "Populiariausios",
  sortPriceAsc: "Pigiausios",
  sortPriceDesc: "Brangiausios",
  sortName: "Pagal pavadinimą",
  results: "prekių",
  nothingFound: "Nieko nerasta",
  tryOther: "Pabandykite kitus filtrus arba paieškos žodžius.",
  specs: "Techniniai duomenys",
  description: "Aprašymas",
  related: "Panašios prekės",
  promo: "Akcijos",
  news: "Naujienos",
  categories: "Kategorijos",
  subcategories: "kategorijų",
  brandsStrip: "Mūsų prekių ženklai",
  qty: "Kiekis",
  total: "Iš viso",
  remove: "Pašalinti",
  checkout: "Pirkti",
  continueShopping: "Tęsti apsipirkimą",
  checkoutSoon: "Užsakymų priėmimas ruošiamas",
  checkoutSoonText: "Kol kas užsakykite telefonu arba el. paštu – atsakysime per darbo dieną.",
  backToCart: "Grįžti į krepšelį",
  phone: "+370 689 00009",
  email: "uzsakymai@rankis.lt",
  hours: "I–V 8:00–17:00",
  delivery: "Pristatymas",
  warranty: "Garantija",
  contacts: "Kontaktai",
  service: "Serviso paslaugos",
  info: "Informacija",
  heroTitle: "Įrankiai ir sodo technika profesionalams ir namams",
  heroText: "Husqvarna, Makita, Stiga, Festool ir dar dešimtys prekių ženklų. Pristatymas per 1–3 d. d.",
  heroCta: "Žiūrėti akcijas",
  notFound: "Puslapis nerastas",
  notFoundText: "Tokio puslapio nėra arba prekė nebeparduodama. Pabandykite paiešką.",
  page: "Puslapis",
  prev: "Ankstesnis",
  next: "Kitas",
  footerAbout: "UAB Teronis – įrankių ir sodo technikos prekyba. Oficialus Husqvarna, Stiga, Makita atstovas.",
  menu: "Meniu",
  close: "Uždaryti",
  searchResultsFor: "Paieškos rezultatai",
  searchHint: "Įveskite prekės pavadinimą, modelį arba kodą",
} as const;
